name = "Panz"
author = "Dawid Szymczyl"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4e3b8aee2a3941bd1e7afd20b2c5f3ca1008a316910fdf98d6bce48632f4db6"

[versions]
minecraft = "1.20.2"
neoforge = "47.1.106"
