name = "Panz"
author = "Dawid Szymczyl"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e1a4ea377bbe7822d05637d6d163ea967df8e9f2523e0276583434d76549ac8"

[versions]
minecraft = "1.20.2"
neoforge = "47.1.106"
